#----------------------------------------------------------#
DOCKER_DOMAIN="ccr.ccs.tencentyun.com"
DOCKER_NAMESPACE="rasp-gz"
DOCKER_REGISTRY="bypy"
DOCKER_IMAGETAG="bypy"
DOCKER_VERSIONTAG="v2"
DOCKER_ARCH="arm64"
#----------------------------------------------------------#
DOCKER_FULL_PUSH_URL="${DOCKER_DOMAIN}/${DOCKER_NAMESPACE}/${DOCKER_REGISTRY}:${DOCKER_IMAGETAG}_${DOCKER_ARCH}_${DOCKER_VERSIONTAG}"
#----------------------------------------------------------#
MY_FOLDER="bypy"
#----------------------------------------------------------#
