name: Build and Test Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm # 需要将仓库改为public后运行此job, 否则失败

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker Login
        run: |
          echo '${{ secrets.DOCKER_PULL_REGISTRY_SECRET }}' | docker login hkccr.ccs.tencentyun.com --username=${{ secrets.TX_TCR_UID }} --password-stdin
      - name: Build Docker image
        run: |
          docker build -t hkccr.ccs.tencentyun.com/rasp/ci:tencent-cloud-arm64-v1 ./tencent-cloud
      - name: Push Docker image
        run: |
          docker push hkccr.ccs.tencentyun.com/rasp/ci:tencent-cloud-arm64-v1
